### ISSUE TITLE
ecdsa_gen_priv and ecdsa_priv2pub don't seem to prepend key bytes with metabyte

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms-ethereum#2]
`api.ecdsa_gen_priv` gives back key bytes that don't contain the metabyte at the beginning to indicate what kind of key.

Or does it and I'm not seeing it?  @tuxxy, can you maybe add some clarity here (and, if it does include the metabyte, in the docstring)?

**Comment by michwill** [comment]
Doesn't start with 00/01? Or the other (sig/enc) metabyte?
