### ISSUE TITLE
What is the proper economic impact of a revoked Policy?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-kms-ethereum#9]
Alice grants access to Bob with (m=7, n=10) for access for a month.

In so doing, she enters an Agreement with 10 Ursulas.  These 10 Ursulas pledge in good faith to remain online and to safely handle a `KFrag` for a month.

Then, just three days later, Alice decides to revoke the entire Policy (and thus, all 10 Agreements).

What happens?  Is Alice entitled to any refund?  If so, then has Ursula gotten a bad deal?  Ursula made preparations to perform service for a month, but now will be paid for some amount less that that.

**Comment by KPrasch** [comment]
see Issue #10; Alice can revoke arrangements.

**Comment by jMyles** [comment]
Per a lively discussion in the battle bridge of the PDX homecoming house, we have decided that Alice always has to pay for the period in which the revocation is requested.  We now have #18 to cover this.
